### ISSUE TITLE
Include editor terminals aswell

### ISSUE THREAD

**Issue by 0104910052** [kwonoj/vscode-activedocumentindicator#16]
Hello, after the last update it is possible to open terminals inside the editor as just another file. It would be useful to include them as well so that's easier to spot your location even if the workbench is composed from multiple windows that include terminals.

Thanks!

**Comment by kwonoj** [comment]
I haven't tried those features myself yet and not sure if it's possible on the extension side. Will try to peek.

**Comment by kwonoj** [comment]
I peeked this bit, so far it looks like vscode does not support decoration (or range selections) on the terminal instance to control visibility. Sadly, until we have upstream support I may not able to attempt to implement this.

**Comment by kwonoj** [comment]
ref: https://github.com/microsoft/vscode/issues/79063 (partially)

**Comment by kwonoj** [comment]
Closing per https://code.visualstudio.com/updates/v1_82#_dim-unfocused-editors-and-terminals, I recommend to use native features instead.
