### ISSUE TITLE
Git Diff 

### ISSUE THREAD

**Issue by ahgharian** [kwonoj/vscode-activedocumentindicator#6]
Good work with this extension. It really helps with keeping your attention/focus. 

Do you think it makes sense to have this enabled for git diffs?

**Comment by kwonoj** [comment]
When I tried for non staged diff view this seemed to work. Any specific view I can try reproduce? Then I'll see if it's doable.

**Comment by ahgharian** [comment]
Here is a non-staged change

![image](https://user-images.githubusercontent.com/3068499/55994078-5d234680-5c76-11e9-8e40-22d8bd331103.png)

**Comment by kwonoj** [comment]
yes, that's what I'm referring: clicking focus to old view it'll change dim to inactive one for new change side. Is that what you expect to have, or you expect to _not_ make any dim in diff?

**Comment by kwonoj** [comment]
let me close this as inactive. as described above currently dimming works across git diff for non staged one.

**Comment by ahgharian** [comment]
Sorry for missing on this. I expect no dimming since when looking at the diff, you actively compare the two so it makes sense to me to have both panels not dimmed or have an option to opt out of this when looking at a diff. 

Thanks for your work on this. 👍

**Comment by kwonoj** [comment]
afaik there's no out-of-box api to distinguish diff view, though it may possible by querying / compare uri. I can't promise anything if I can spend time to add this support but will try if time allows.
